name: Skip Checkout
description: Skips the default Buildkite and optionally changes to a specified directory
author: https://github.com/reidab
requirements: []
configuration:
  properties:
    pattern: 
      type: string
  required:
    - pattern