name: Spell Checker
description: Checks the spelling of all mark down files present in the root directory of the project
author: https://github.com/nithyaasworld
requirements: []
configuration:
  properties:
    pattern: 
      type: string
  required:
    - pattern
