steps:
  - label: run bats tests
    plugins:
      - docker-compose#v3.3.0:
          run: tests
  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v2.0.0:
          id: nithyaasworld/spellchecker
  - label: "spell check md files"
    plugins:
      - nithyaasworld/spellchecker#v0.2.8:
          pattern: '*.md'