steps:
  - label: ":sparkles: lint"
    plugins:
      plugin-linter#v2.0.0:
        id: nithyaasworld/spellchecker
  - label: "spell check readme file"
    plugins:
      nithyaasworld/spellchecker#v0.0.6:
        pattern: '*.md'
  - label: run bats tests
    plugins:
      - docker-compose#v3.3.0:
          run: tests