steps:
  - label: ":sparkles: lint"
    plugins:
      plugin-linter#v2.0.0:
        id: nithyaasworld/spellchecker
  - label: "spell check readme file"
    plugins:
      nithyaasworld/spellchecker#v0.0.1:
        pattern: '**/*.md'